// gen-opnsense-mocks reads Unbound.xml and DNat.xml from the OPNsense core reference
// submodule and emits gateway/opnsense_types_gen.go.
//
// Its primary job is validation: if the XML models no longer contain the fields our
// client depends on, the tool fails loudly so the CI diff-check catches it.
package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

const (
	unboundXML = "../reference/opnsense-core/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml"
	dnatXML    = "../reference/opnsense-core/src/opnsense/mvc/app/models/OPNsense/Firewall/DNat.xml"
	outputFile = "opnsense_types_gen.go"
)

// Fields we extract from Unbound.xml hosts.host ArrayField.
var unboundHostFields = []string{
	"enabled",
	"hostname",
	"domain",
	"rr",
	"server",
	"description",
}

// Fields we extract from DNat.xml rule ArrayField.
// source/destination sub-fields are validated by checking their parent element names.
var dnatRuleFields = []string{
	"interface",
	"protocol",
	"source",
	"destination",
	"target",
	"local-port",
	"descr",
}

func main() {
	unboundContent, err := os.ReadFile(unboundXML)
	if err != nil {
		fatalf("reading %s: %v", unboundXML, err)
	}
	dnatContent, err := os.ReadFile(dnatXML)
	if err != nil {
		fatalf("reading %s: %v", dnatXML, err)
	}

	if err := validateFields(string(unboundContent), unboundXML, unboundHostFields); err != nil {
		fatalf("%v", err)
	}
	if err := validateFields(string(dnatContent), dnatXML, dnatRuleFields); err != nil {
		fatalf("%v", err)
	}

	out, err := os.Create(outputFile)
	if err != nil {
		fatalf("creating %s: %v", outputFile, err)
	}
	defer out.Close()

	data := templateData{
		UnboundXML: unboundXML,
		DnatXML:    dnatXML,
	}
	if err := outputTemplate.Execute(out, data); err != nil {
		fatalf("executing template: %v", err)
	}

	fmt.Printf("wrote %s\n", outputFile)
}

// validateFields checks that each required field name appears as an XML element
// in the given content. A missing field means the OPNsense model changed and our
// client types need to be reviewed.
func validateFields(content, source string, fields []string) error {
	for _, field := range fields {
		tag := "<" + field
		if !strings.Contains(content, tag) {
			return fmt.Errorf("field %q not found in %s — OPNsense model may have changed; review client types", field, source)
		}
	}
	return nil
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "gen-opnsense-mocks: "+format+"\n", args...)
	os.Exit(1)
}

type templateData struct {
	UnboundXML string
	DnatXML    string
}

var outputTemplate = template.Must(template.New("types").Parse(`// Code generated by tools/gen-opnsense-mocks. DO NOT EDIT.
// Sources:
//   {{ .UnboundXML }}
//   {{ .DnatXML }}

package gateway

// HostOverride holds fields for creating a single Unbound DNS host override.
// Extracted from Unbound.xml items.hosts.host ArrayField.
type HostOverride struct {
	Enabled     string ` + "`" + `json:"enabled"` + "`" + `
	Hostname    string ` + "`" + `json:"hostname"` + "`" + `
	Domain      string ` + "`" + `json:"domain"` + "`" + `
	RR          string ` + "`" + `json:"rr"` + "`" + `
	Server      string ` + "`" + `json:"server"` + "`" + `
	Description string ` + "`" + `json:"description"` + "`" + `
}

// HostOverrideRequest wraps HostOverride for add_host_override requests.
type HostOverrideRequest struct {
	Host HostOverride ` + "`" + `json:"host"` + "`" + `
}

// HostOverrideRow is a single row in the search_host_override response.
type HostOverrideRow struct {
	UUID        string ` + "`" + `json:"uuid"` + "`" + `
	Enabled     string ` + "`" + `json:"enabled"` + "`" + `
	Hostname    string ` + "`" + `json:"hostname"` + "`" + `
	Domain      string ` + "`" + `json:"domain"` + "`" + `
	RR          string ` + "`" + `json:"rr"` + "`" + `
	Server      string ` + "`" + `json:"server"` + "`" + `
	Description string ` + "`" + `json:"description"` + "`" + `
}

// HostOverrideSearchResult is the response body of search_host_override.
type HostOverrideSearchResult struct {
	Rows     []HostOverrideRow ` + "`" + `json:"rows"` + "`" + `
	RowCount int               ` + "`" + `json:"rowCount"` + "`" + `
	Total    int               ` + "`" + `json:"total"` + "`" + `
	Current  int               ` + "`" + `json:"current"` + "`" + `
}

// NATRuleEndpoint represents the source or destination endpoint of a NAT rule.
// Extracted from DNat.xml rule.source and rule.destination sub-elements.
type NATRuleEndpoint struct {
	Network string ` + "`" + `json:"network,omitempty"` + "`" + `
	Port    string ` + "`" + `json:"port,omitempty"` + "`" + `
}

// NATRule holds fields for creating a single NAT port forwarding rule.
// Extracted from DNat.xml items.rule ArrayField.
type NATRule struct {
	Interface   string          ` + "`" + `json:"interface"` + "`" + `
	Protocol    string          ` + "`" + `json:"protocol"` + "`" + `
	Source      NATRuleEndpoint ` + "`" + `json:"source"` + "`" + `
	Destination NATRuleEndpoint ` + "`" + `json:"destination"` + "`" + `
	Target      string          ` + "`" + `json:"target"` + "`" + `
	LocalPort   string          ` + "`" + `json:"local-port"` + "`" + `
	Description string          ` + "`" + `json:"descr"` + "`" + `
}

// NATRuleRequest wraps NATRule for add_rule requests.
type NATRuleRequest struct {
	Rule NATRule ` + "`" + `json:"rule"` + "`" + `
}

// NATRuleRow is a single row in the search_rule response.
type NATRuleRow struct {
	UUID        string ` + "`" + `json:"uuid"` + "`" + `
	Interface   string ` + "`" + `json:"interface"` + "`" + `
	Protocol    string ` + "`" + `json:"protocol"` + "`" + `
	Target      string ` + "`" + `json:"target"` + "`" + `
	LocalPort   string ` + "`" + `json:"local-port"` + "`" + `
	Description string ` + "`" + `json:"descr"` + "`" + `
}

// NATRuleSearchResult is the response body of search_rule.
type NATRuleSearchResult struct {
	Rows     []NATRuleRow ` + "`" + `json:"rows"` + "`" + `
	RowCount int          ` + "`" + `json:"rowCount"` + "`" + `
	Total    int          ` + "`" + `json:"total"` + "`" + `
	Current  int          ` + "`" + `json:"current"` + "`" + `
}

// OPNsenseResult is the standard response for add/del operations.
type OPNsenseResult struct {
	Result string ` + "`" + `json:"result"` + "`" + `
	UUID   string ` + "`" + `json:"uuid,omitempty"` + "`" + `
}
`))
