// Code generated by tools/gen-opnsense-mocks. DO NOT EDIT.
// Sources:
//   ../reference/opnsense-core/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
//   ../reference/opnsense-core/src/opnsense/mvc/app/models/OPNsense/Firewall/DNat.xml

package gateway

// HostOverride holds fields for creating a single Unbound DNS host override.
// Extracted from Unbound.xml items.hosts.host ArrayField.
type HostOverride struct {
	Enabled     string `json:"enabled"`
	Hostname    string `json:"hostname"`
	Domain      string `json:"domain"`
	RR          string `json:"rr"`
	Server      string `json:"server"`
	Description string `json:"description"`
}

// HostOverrideRequest wraps HostOverride for add_host_override requests.
type HostOverrideRequest struct {
	Host HostOverride `json:"host"`
}

// HostOverrideRow is a single row in the search_host_override response.
type HostOverrideRow struct {
	UUID        string `json:"uuid"`
	Enabled     string `json:"enabled"`
	Hostname    string `json:"hostname"`
	Domain      string `json:"domain"`
	RR          string `json:"rr"`
	Server      string `json:"server"`
	Description string `json:"description"`
}

// HostOverrideSearchResult is the response body of search_host_override.
type HostOverrideSearchResult struct {
	Rows     []HostOverrideRow `json:"rows"`
	RowCount int               `json:"rowCount"`
	Total    int               `json:"total"`
	Current  int               `json:"current"`
}

// NATRuleEndpoint represents the source or destination endpoint of a NAT rule.
// Extracted from DNat.xml rule.source and rule.destination sub-elements.
type NATRuleEndpoint struct {
	Network string `json:"network,omitempty"`
	Port    string `json:"port,omitempty"`
}

// NATRule holds fields for creating a single NAT port forwarding rule.
// Extracted from DNat.xml items.rule ArrayField.
type NATRule struct {
	Interface   string          `json:"interface"`
	Protocol    string          `json:"protocol"`
	Source      NATRuleEndpoint `json:"source"`
	Destination NATRuleEndpoint `json:"destination"`
	Target      string          `json:"target"`
	LocalPort   string          `json:"local-port"`
	Description string          `json:"descr"`
}

// NATRuleRequest wraps NATRule for add_rule requests.
type NATRuleRequest struct {
	Rule NATRule `json:"rule"`
}

// NATRuleRow is a single row in the search_rule response.
type NATRuleRow struct {
	UUID        string `json:"uuid"`
	Interface   string `json:"interface"`
	Protocol    string `json:"protocol"`
	Target      string `json:"target"`
	LocalPort   string `json:"local-port"`
	Description string `json:"descr"`
}

// NATRuleSearchResult is the response body of search_rule.
type NATRuleSearchResult struct {
	Rows     []NATRuleRow `json:"rows"`
	RowCount int          `json:"rowCount"`
	Total    int          `json:"total"`
	Current  int          `json:"current"`
}

// OPNsenseResult is the standard response for add/del operations.
type OPNsenseResult struct {
	Result string `json:"result"`
	UUID   string `json:"uuid,omitempty"`
}
